[package]

name = "profile"
version = "0.0.1"
authors = ["Ji Ho Koo <jihokoo@gmail.com>"]

[dependencies.rustful]
git = "https://github.com/Ogeon/rustful.git"

[dependencies.rustful_macros]
git = "https://github.com/Ogeon/rustful"
